# This file was generated by GoReleaser. DO NOT EDIT.
cask "emojify-go" do
  desc "Lighting fast Emoji conversion on the command line 😱"
  homepage "https://github.com/damienbutt/emojify-go"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emojify"
  manpage "man/emojify.1"

  on_macos do
    on_intel do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_darwin_amd64.tar.gz"
      sha256 "cc15e580839f2c076478b9251dc784af58ba013ed7c19a599df97b099b7edd81"
    end
    on_arm do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_darwin_arm64.tar.gz"
      sha256 "d9faeea23c0cbccc03080ceed46d2cb1427941a70fe0f20d375232f28295cb16"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_linux_amd64.tar.gz"
      sha256 "5b7ed90811f9ce379203221b7f55f8501a2482eeba3d7c241138721c4e82876a"
    end
    on_arm do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_linux_arm64.tar.gz"
      sha256 "6ec9bcc61456a52ee7ee4e08f072d5764467813546c8f05d57e37d59821b027d"
    end
  end

  # No zap stanza required
end
