# This file was generated by GoReleaser. DO NOT EDIT.
cask "emojify-go" do
  desc "Lighting fast Emoji conversion on the command line 😱"
  homepage "https://github.com/damienbutt/emojify-go"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emojify"
  manpage "man/emojify.1"

  on_macos do
    on_intel do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_darwin_amd64.tar.gz"
      sha256 "5d10db43959e317ad5709c29d9dfc663108fd185e1ad6f4a4c2adf5a407118ea"
    end
    on_arm do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_darwin_arm64.tar.gz"
      sha256 "d2d49413e7a808d7b0f1119fa07456e8719afad1ec04cf2fe7254235881e3900"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_linux_amd64.tar.gz"
      sha256 "139d3a648fe0541a9333d17ec45df052c7d834f101d941f5131f639d0a84e0e4"
    end
    on_arm do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_linux_arm64.tar.gz"
      sha256 "bd950b9e75ae5efff7ff58e7df146fea76c6e6a9d8f1ac93e5e9cbd4bfe531d3"
    end
  end

  # No zap stanza required
end
