# This file was generated by GoReleaser. DO NOT EDIT.
cask "emojify-go" do
  desc "Lighting fast Emoji conversion on the command line 😱"
  homepage "https://github.com/damienbutt/emojify-go"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emojify"
  manpage "man/emojify.1"

  on_macos do
    on_intel do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_darwin_amd64.tar.gz"
      sha256 "a91bdc8e00eecae39579ef9448c156a1169e170a343213f07cc6ca39a1b4980f"
    end
    on_arm do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_darwin_arm64.tar.gz"
      sha256 "62eaba071856306080ada83809681373efe679430bd9c4c84baf346cc4421338"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_linux_amd64.tar.gz"
      sha256 "a11a1ad05bd765636d4c4d05e42eb2d8317001ed5dcb929013d3b976d323931d"
    end
    on_arm do
      url "https://github.com/damienbutt/emojify-go/releases/download/v1.0.0/emojify-go_1.0.0_linux_arm64.tar.gz"
      sha256 "be846a7204b7c058473f32a524681f54f6ae8e06074d265497a86adda8f5fb0e"
    end
  end

  # No zap stanza required
end
