# This file was generated by GoReleaser. DO NOT EDIT.
cask "figlet" do
  name "figlet"
  desc "Go FIGdriver. Generates ASCII art from text using FIGlet fonts."
  homepage "https://github.com/damienbutt/figlet"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "figlet"

  on_macos do
    on_intel do
      url "https://github.com/damienbutt/figlet/releases/download/v#{version}/figlet_#{version}_darwin_amd64.tar.gz"
      sha256 "27175367781b60fd9d47e7c6ef617f9863bfb9119d6062a1cfd48a078ff561ee"
    end
    on_arm do
      url "https://github.com/damienbutt/figlet/releases/download/v#{version}/figlet_#{version}_darwin_arm64.tar.gz"
      sha256 "105b4ff135882a912368f0e2fab5563353e8a6729bc3e8dea9bfcb5773b7fadf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/damienbutt/figlet/releases/download/v#{version}/figlet_#{version}_linux_amd64.tar.gz"
      sha256 "64fd36610c2489777f0a53b885748349df87098bdf4920cd062152ddba5fa3a6"
    end
    on_arm do
      url "https://github.com/damienbutt/figlet/releases/download/v#{version}/figlet_#{version}_linux_arm64.tar.gz"
      sha256 "d19082969a48900a7134e2ee72092e6a2533a7a841018094d21ee0dc2fea573b"
    end
  end

  # No zap stanza required
end
