# This file was generated by GoReleaser. DO NOT EDIT.
cask "figlet" do
  name "figlet"
  desc "Go FIGdriver. Generates ASCII art from text using FIGlet fonts."
  homepage "https://github.com/damienbutt/figlet"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "figlet"

  on_macos do
    on_intel do
      url "https://github.com/damienbutt/figlet/releases/download/v#{version}/figlet_#{version}_darwin_amd64.tar.gz"
      sha256 "07fa5d1f209a7200b9ae22181e76659071ad87811263e8881669482bcfb013bc"
    end
    on_arm do
      url "https://github.com/damienbutt/figlet/releases/download/v#{version}/figlet_#{version}_darwin_arm64.tar.gz"
      sha256 "3f690aca6be6e47e0a9052414505d227747b101c192e5a41b6ec8a626e485d00"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/damienbutt/figlet/releases/download/v#{version}/figlet_#{version}_linux_amd64.tar.gz"
      sha256 "5c8b3442aba29f19219baf9f64d68ba5f9e04689fb79f00a66ab42cba78b6480"
    end
    on_arm do
      url "https://github.com/damienbutt/figlet/releases/download/v#{version}/figlet_#{version}_linux_arm64.tar.gz"
      sha256 "286fed6f9d352442ac11a5f6bd1f6510ae1c1fa0e6c109982f80288f954e24a1"
    end
  end

  # No zap stanza required
end
